Big changes

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,9 +1,18 @@
 #!/usr/bin/env bash
 
+# Quit on error
 set -e
 
 echo "[i] Ask for sudo password"
 sudo -v
+
+tags="$1"
+work_directory=$(pwd)
+custom_file_path="$work_directory/custom.yml"
+
+if [ -z $tags ]; then
+  tags="all"
+fi
 
 case "$(uname -s)" in
   Linux)
@@ -29,8 +38,59 @@ case "$(uname -s)" in
     ;;
 esac
 
+welcome_message() {
+  echo "Welcome to ansible setup"
+  echo
+  echo "This script is interactive"
+  echo "If you prefer to fill in the custom.yml file manually,"
+  echo "press [Ctrl+C] to quit this script"
+}
+
+get_username() {
+  echo
+  echo "Enter your desired username"
+  read -p "Username: " username
+  while ! [[ "$username" =~ ^[a-z0-9]*$ ]]; do
+    echo "[!] Invalid username"
+    echo "[!] Make sure the username only contains lowercase letters and numbers"
+    read -p "Username: " username
+  done
+
+  echo "username: \"${username}\"" >> $custom_file_path
+}
+
+get_user_password() {
+  echo
+  echo "Enter your user password"
+  echo "This password will be used for login your user"
+  read -s -p "Password: " user_password
+  echo
+  read -s -p "Repeat password: " user_password2
+  echo
+
+  while ! [[ "$user_password" == "$user_password2" ]]; do
+    echo
+    echo "[!] The passwords don't match"
+    read -s -p "Password: " user_password
+    echo
+    read -s -p "Repeat password: " user_password2
+  done
+
+  echo "user_password: \"${user_password}\"" >> $custom_file_path
+}
+
+touch $custom_file_path
+# Clean already existed file
+cat /dev/null > $custom_file_path
+
+clear
+welcome_message
+get_username
+get_user_password
+
 echo "[i] Run Playbook"
-ansible-playbook bootstrap.yml --ask-become-pass --tags all
+ansible-playbook bootstrap.yml --ask-become-pass --tags $tags 
+# --skip-tags arch_linux
 
 echo "[i] From now on you can use $ dotfiles to manage your dotfiles"
 echo "[i] Done."
